"use strict";

let bcrypt      = require('bcrypt'),
    generator   = require('generate-password'),
    Database    = require("../core/ormdatabase.js"),
    Model       = require("./model.js"),
    Common      = require('../core/common.js')(),
    Timezone    = require("./timezone.js"),
    UserGroup   = require("./usergroup.js"),
    UserStatus  = require("./userstatus.js"),
    database = new Database();


/**
* Constructor
*/
var User = database.sequelize.define("user",{
    userId: {
      type: Database.Sequelize.INTEGER,
      primaryKey: true,
      field: "user_id",
      autoIncrement: true
    },
    username: {
      type: Database.Sequelize.STRING,
      validate: {
        is: ["^[a-z0-9\-\_\.]+$",'i'],
        isLowercase: true
      }
    },
    password: {
      type: Database.Sequelize.STRING
    },
    firstname: {
      type: Database.Sequelize.STRING
    },
    lastname: {
      type: Database.Sequelize.STRING
    },
    email: {
      type: Database.Sequelize.STRING,
      validate: {
        isEmail: true
      }
    },
    verifiedEmail: {
      type: Database.Sequelize.INTEGER,
      field: "verified_email"
    },
    phone1: {
      type: Database.Sequelize.STRING
    },
    phone2: {
      type: Database.Sequelize.STRING
    },
    statusId: {
      type: Database.Sequelize.INTEGER,
      field: "status_id",
    },
    timezoneId: {
      type: Database.Sequelize.INTEGER,
      field: "timezone_id"
    },
    userGroupId: {
      type: Database.Sequelize.INTEGER,
      field: "user_group_id"
    },
    lastLogin: {
      type: Database.Sequelize.DATE,
      field: "last_login"
    },
    active: {
      type: Database.Sequelize.INTEGER
    },
    dateCreated: {
      type: Database.Sequelize.DATE,
      field: "date_created"
    }
},{
  tableName: Model.getTableName("USER"),
  hooks: {
    beforeValidate: (user, options) => {
      user.username = user.username.trim().toLowerCase()
      if (user.email === undefined || user.email === null) return;
      user.email = user.email.toLowerCase();
    },
    beforeUpdate: (user, options) => {
      if (user.changed("email"))
        user.verifiedEmail = 0
    }
  }
});

/**
 * Method to find a username by id
 * @param  int id     [description]
 * @param  boolean active [description]
 * @return {[type]}        [description]
 */
User.findById = async function(id,active){
  if (typeof active !== "boolean") active = true;
  var filter = {userId:id};
  if (active !== null) filter.active = active ? 1 : 0;
  return User.findOne({where: filter});
};

/**
 * Method to find a user by username
 * @param  {[type]} username [description]
 * @param  boolean active   [description]
 * @return {[type]}          [description]
 */
User.findByUsername = async function(username,active){
  if (typeof active !== "boolean") active = true;
  var filter = {username:username};
  if (active !== null) filter.active = active ? 1 : 0;
  return User.findOne({where: filter});
};


/**
 * Method to determine if the current user must contain pinless account
 * @return {boolean}
 */
User.prototype.mustContainPlAccount = function(){
  return this.userGroupId === UserGroup.TYPES.USER;
}

/**
 * Method to make a quick register (only apply for end-user)
 * @param  Context ctx
 * @param  String accountNumber the unique account number (username)
 * @return Promise          The token generated to validate the code sent
 */
User.prototype.quickRegister = async function(ctx,accountNumber){
  var orgIp = Common.ip.address();

  //verify if the user in the app already exists
  var user = await User.findOne({where: {username: accountNumber}});
  var saved = false;
  if (user === null){
    //proceed to register the new user
    var password = generator.generate({length: 8,numbers: true});
    ////global.logger.debug("Password generated by '" + accountNumber + "':",password);
    password =  bcrypt.hashSync(password, Config.crypt.salt.rounds);

    user = User.build({
      username: accountNumber,
      password: password,
      placcountNumber: accountNumber,
      statusId: UserStatus.TYPES.PENDING,
      timezoneId: Timezone.ID.AMERICA__NEW_YORK,
      userGroupId: UserGroup.TYPES.USER
    });
    saved = await user.save().catch(err=>{
      console.log("err",err);
    });

    if (!saved){
      global.logger.default.error("the user " + accountNumber + " cannot be saved");
      resolve(null);
      return;
    }
  }
  return new Promise(async function(resolve,reject){
    var db = new MsDatabase();
    db.execute(async function(pool,result){
      var resultRegister = await pool.request()
        .input('iAcct_GUID',MsDatabase.Mssql.VarChar,Config.db.pinless.acct_guid)
        .input('iAcct_User',MsDatabase.Mssql.VarChar,Config.db.pinless.acct_user)
        .input('iAcct_Pass',MsDatabase.Mssql.VarChar,Config.db.pinless.acct_pass)
        .input('iPL_User',MsDatabase.Mssql.VarChar,accountNumber)
        .input('iOrg_IP',MsDatabase.Mssql.VarChar,orgIp)
        .output('oSession_ID', MsDatabase.Mssql.VarChar)
        .output('oDevice_GUID', MsDatabase.Mssql.VarChar)
        .execute("spSoftPhone_Simple_Register");
        if (!(typeof resultRegister === "object" && typeof resultRegister['returnValue'] === "number" && resultRegister['returnValue'] === Config.db.pinless.return_value.success)){
          var wserror = db.mapError(resultRegister['returnValue'],"SIMPLE_REGISTER");
          reject(wserror);
          return;
        }

        //recordsets=[], recordset=undefined, oSession_ID=1F8BCF55-9664-4F64-B2D8-173FD42E0E71, oDevice_GUID=1826AE07-28A3-494F-9E95-638747B86F90, rowsAffected=[], returnValue=200
        //@iAcct_GUID, @iAcct_User, @iAcct_Pass, @iPL_User, @iOrg_IP, @oSession_ID, @oDevice_GUID
        //console.log(resultRegister);
        var outputResult = typeof resultRegister['output'] === "object" ? resultRegister['output'] : {};
        var output = {user: user};
        output.token = User.encodeToken(outputResult['oSession_ID'],outputResult['oDevice_GUID'],user.userId);
        if (output.token === null){
          global.logger.default.error("error generating token",{
            output: output
          });
          reject(5002);
          return;
        }
        resolve(output);
    }).catch(err => {
        global.logger.default.error("Error registering the user",{
          error: err
        });
        reject(db.mapError("500"));
    });
  });
}


/**
 * Method to confirm the user (by SMS so far)
 * @param  {[type]} ctx              Context
 * @param  {[type]} token            token
 * @param  {[type]} verificationCode Verification Code
 * @return Promise                   [description]
 */
User.prototype.callCode = async function(ctx, token){
  var orgIp = Common.ip.address();

  var errorRegisteringUserCode = "5002";

  return new Promise(async function(resolve,reject){
    var decodedToken = User.decodeToken(token);
    if (decodedToken === null){
      global.logger.default.error("invalid token", {
        token: token
      });
      reject("4006");
      return;
    }

    var db = new MsDatabase();
    db.execute(async function(pool,result){
      var resultGetCode = await pool.request()
      .input('iSession_Id',MsDatabase.Mssql.VarChar,decodedToken.session_id)
      .input('iAcct_GUID',MsDatabase.Mssql.VarChar,Config.db.pinless.acct_guid)
      .input('iDevice_Id',MsDatabase.Mssql.VarChar,decodedToken.device_id)
      .input('iOrg_IP',MsDatabase.Mssql.VarChar,orgIp)
      .output('oAccount_Id',MsDatabase.Mssql.VarChar)
      .output('oLocale',MsDatabase.Mssql.VarChar)
      .output('oCode',MsDatabase.Mssql.VarChar)
      .execute("spSoftPhone_Get_Code");

      if (!(typeof resultGetCode === "object" && typeof resultGetCode['returnValue'] === "number" && resultGetCode['returnValue'] === Config.db.pinless.return_value.success)){
        var wserror = db.mapError(resultGetCode['returnValue'],"RETRIEVE_CODE");
        reject(wserror);
        return;
      }

      var outputResult = typeof resultGetCode['output'] === "object" ? resultGetCode['output'] : {};

      //proceed to request the call
      var ivrApiService = new IVRApiService();
      var resultCode = await ivrApiService.sendCode(outputResult['oAccount_Id'],outputResult['oCode'],outputResult['oLocale']);
      if (!resultCode){
        reject("5006");
        return;
      }
      //end: proceed to request the call
      resolve(resultCode);
    }).catch(err => {
        global.logger.default.error("Error retrieving the sms code",{
          error: err
        });
        reject(db.mapError("500"));
    });
  });
}


/**
 * Method to confirm the user (by SMS so far)
 * @param  {[type]} ctx              Context
 * @param  {[type]} token            token
 * @param  {[type]} verificationCode Verification Code
 * @return Promise                   [description]
 */
User.prototype.resendCode = async function(ctx, token){
  return this.confirmUser(ctx,token,"RESEND");
}

/**
 * Method to find if there any account with the current email before create it
 * @param  {[type]} email [description]
 * @return {[type]}       [description]
 */
User.prototype.findExistingEmail = async function(email){
  var _this = this;
  return await User.findOne({
    where: {
      email: email,
      userId: {
        [Database.Sequelize.Op.ne] : _this.userId
      }
    }
  });
}

/**
 * Method to confirm the user (by SMS so far)
 * @param  {[type]} ctx              Context
 * @param  {[type]} token            token
 * @param  {[type]} verificationCode Verification Code
 * @return Promise                   [description]
 */
User.prototype.confirmUser = async function(ctx, token, verificationCode){
  var orgIp = Common.ip.address();
  var resend = verificationCode === "RESEND";
  var errorRegisteringUserCode = "5002";

  return new Promise(async function(resolve,reject){
    var decodedToken = User.decodeToken(token);
    if (decodedToken === null){
      global.logger.default.error("invalid token",{
        token: token
      });
      reject("4006");
      return;
    }
    //console.log("decodedToken",decodedToken);
    //verify if the user in the app already exists
    var user = await User.findById(decodedToken.user_id);

    if (user === null){
      global.logger.default.error("the user is null",{
        decodeToken: decodedToken,
        user: user
      });
      reject("4006");
      return;
    }

    var db = new MsDatabase();
    db.execute(async function(pool,result){
      var resultConfirm = await pool.request()
      .input('iSession_Id',MsDatabase.Mssql.VarChar,decodedToken.session_id)
      .input('iAcct_GUID',MsDatabase.Mssql.VarChar,Config.db.pinless.acct_guid)
      .input('iDevice_Id',MsDatabase.Mssql.VarChar,decodedToken.device_id)
      .input('iVrf_Code',MsDatabase.Mssql.VarChar,verificationCode)
      .input('iOrg_IP',MsDatabase.Mssql.VarChar,orgIp)
      .execute("spSoftPhone_Vrf_Code_crAccount");

      if (!(typeof resultConfirm === "object" && typeof resultConfirm['returnValue'] === "number" && resultConfirm['returnValue'] === Config.db.pinless.return_value.success)){
        var wserror = db.mapError(resultConfirm['returnValue'],"VERIFICATION_CODE");
        reject(wserror);
        return;
      }

      if (resend){
        resolve(user);
        return;
      }

      //proceed to update the device id and status
      user.deviceId = decodedToken.device_id;
      user.statusId = UserStatus.TYPES.ACTIVE;
      var saved = await user.save();

      if (!saved){
        global.logger.default.error("error updating the user",{
          user: user
        });
        //reject with error registering the user
        reject("5002");
        return;
      }
      //end: proceed to update the device id and status
        resolve(user);
    }).catch(err => {
        global.logger.default.error("Error confirming user",{
          error: err
        });
        reject(db.mapError("500"));
    });
  });
};

/**
 * Method to decode the token generated in quick register
 * @param  {[type]} token [description]
 * @return {[type]}       [description]
 */
User.decodeToken = function(token){
  var token = new Buffer(token, 'base64').toString('ascii');
  token = token.split("|");
  if (token.length < 3) return null;

  var outputToken = {};
  outputToken.session_id = token[0];
  outputToken.device_id  = token[1];
  outputToken.user_id    = token[2];

  for(var k in outputToken) if (outputToken[k] === null) return null;

  return outputToken;
};

/**
 * Method to encode the token generated in quick register
 * @param  {String} session_id  [description]
 * @param  {String} device_id   [description]
 * @param  {Number} user_id     [description]
 * @return {[type]}             [description]
 */
User.encodeToken = function(session_id,device_id,user_id){
  if (typeof session_id !== "string" || typeof device_id !== "string") return null;
  var token = session_id + "|" + device_id + "|" + user_id;
  token = new Buffer(token).toString('base64');
  return token;
};

User.hasOne(UserGroup,{foreignKey:"userGroupId" });

module.exports = User;
